name: deploy
on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          # Without this the fetch depth defaults to 1, which only includes the most recent commit. We want to know the full history so that `git describe` can give more information when it is invoked in the orderbook's crate build script.
          fetch-depth: '0'

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Solvers image metadata
        id: meta_solvers
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: Solvers image build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.binary
          push: true
          tags: ${{ steps.meta_solvers.outputs.tags }}
          labels: ${{ steps.meta_solvers.outputs.labels }}

      - uses: cowprotocol/autodeploy-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          images: ghcr.io/cowprotocol/solvers:main
          tag: ${{ secrets.AUTODEPLOY_TAG }}
          url: ${{ secrets.AUTODEPLOY_URL }}
          token: ${{ secrets.AUTODEPLOY_TOKEN }}
          timeout: 600000 # 10 minutes
